/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jzwmuyflifxsuclhphux";
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6d211eWZsaWZ4c3VjbGhwaHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMjg2ODEsImV4cCI6MjA3MzYwNDY4MX0.i-cgR8Zae0Z3XYOLHASWb9klc4MwU242QBdBLfYQ2fg";