import { useState, useEffect } from "react";
import moment from "moment";
import { Button } from "./ui/button";
import { Checkbox } from "./ui/checkbox";
import { Label } from "./ui/label";
import { X, User, DoorOpen, FileText, ThumbsUp, RefreshCw, Users, LogIn, UserPlus, MessageCircleQuestion, Flag, Globe, CheckCircle2, Bot } from "lucide-react";
import { api } from "../utils/api";
import type { ActivityFeedEvent, ActivityFeedEventType, ActivityDayCount } from "../types";
import { ActivityTimeline } from "./activity-feed/ActivityTimeline";

interface AdminActivityFeedProps {
  onExit: () => void;
}

const TYPE_CONFIG: Record<
  ActivityFeedEventType,
  { label: string; icon: React.ComponentType<{ className?: string }>; color: string; bg: string }
> = {
  user: { label: "User", icon: User, color: "text-green-700", bg: "bg-green-100" },
  session: { label: "Session", icon: LogIn, color: "text-teal-700", bg: "bg-teal-100" },
  room: { label: "Room", icon: DoorOpen, color: "text-blue-700", bg: "bg-blue-100" },
  community: { label: "Community", icon: Users, color: "text-orange-700", bg: "bg-orange-100" },
  statement: { label: "Statement", icon: FileText, color: "text-purple-700", bg: "bg-purple-100" },
  vote: { label: "Vote", icon: ThumbsUp, color: "text-amber-700", bg: "bg-amber-100" },
  modInviteAccept: { label: "Mod Invite Accept", icon: UserPlus, color: "text-violet-700", bg: "bg-violet-100" },
  cohost: { label: "Co-host", icon: UserPlus, color: "text-violet-700", bg: "bg-violet-100" },
  askTheData: { label: "Ask the Data", icon: MessageCircleQuestion, color: "text-blue-700", bg: "bg-blue-100" },
  userReport: { label: "Report", icon: Flag, color: "text-red-700", bg: "bg-red-100" },
  pageLoad: { label: "Page Load", icon: Globe, color: "text-gray-700", bg: "bg-gray-100" },
};

const ALL_TYPES: ActivityFeedEventType[] = [
  "user",
  "session",
  "room",
  "community",
  "statement",
  "vote",
  "modInviteAccept",
  "cohost",
  "askTheData",
  "userReport",
  "pageLoad",
];

function formatTime(ts: number): string {
  return moment(ts).fromNow();
}

const LAST_REVIEWED_KEY = "adminActivityFeedLastReviewedAt";

export function AdminActivityFeed({ onExit }: AdminActivityFeedProps) {
  const [events, setEvents] = useState<ActivityFeedEvent[]>([]);
  const [dayCounts, setDayCounts] = useState<ActivityDayCount[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [filter, setFilter] = useState<ActivityFeedEventType | "all">("all");
  const [lastReviewedAt, setLastReviewedAt] = useState<number | null>(() => {
    const stored = localStorage.getItem(LAST_REVIEWED_KEY);
    return stored ? Number(stored) : null;
  });
  const [hideAutoGenerated, setHideAutoGenerated] = useState(true);

  const markReviewed = () => {
    const now = Date.now();
    localStorage.setItem(LAST_REVIEWED_KEY, String(now));
    setLastReviewedAt(now);
  };

  const load = async () => {
    setLoading(true);
    setError(null);
    const res = await api.getActivityFeed();
    if (res.success && res.data) {
      setEvents(res.data.events);
      setDayCounts(res.data.dayCounts ?? []);
    } else {
      setError("Failed to load activity feed");
    }
    setLoading(false);
  };

  useEffect(() => {
    load();
  }, []);

  const scopedEvents = hideAutoGenerated ? events.filter((e) => !e.isAutoGenerated) : events;

  const visible = filter === "all" ? scopedEvents : scopedEvents.filter((e) => e.type === filter);

  const counts = ALL_TYPES.reduce<Record<string, number>>((acc, t) => {
    acc[t] = scopedEvents.filter((e) => e.type === t).length;
    return acc;
  }, {});

  return (
    <div style={{ minHeight: "100vh", backgroundColor: "#f9fafb", display: "flex", flexDirection: "column" }}>
      <div style={{ backgroundColor: "white", borderBottom: "1px solid #e5e7eb", padding: "16px 24px", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <div>
          <h1 style={{ fontSize: "20px", fontWeight: 700, margin: 0 }}>Activity Feed</h1>
          <p style={{ fontSize: "13px", color: "#6b7280", margin: "2px 0 0 0" }}>New records from the last 7 days</p>
        </div>
        <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>
          {lastReviewedAt && (
            <span style={{ fontSize: "12px", color: "#9ca3af" }}>
              Last reviewed {formatTime(lastReviewedAt)}
            </span>
          )}
          <Button variant="outline" size="sm" onClick={markReviewed}>
            <CheckCircle2 className="w-3 h-3 mr-1" />
            Mark Reviewed
          </Button>
          <Button variant="outline" size="sm" onClick={load} disabled={loading}>
            <RefreshCw className={`w-3 h-3 mr-1 ${loading ? "animate-spin" : ""}`} />
            Refresh
          </Button>
          <Button variant="outline" size="sm" onClick={onExit}>
            <X className="w-4 h-4" />
          </Button>
        </div>
      </div>

      {!loading && !error && dayCounts.length > 0 && (
        <ActivityTimeline dayCounts={dayCounts} />
      )}

      <div style={{ padding: "16px 24px 0", display: "flex", alignItems: "center", gap: "6px" }}>
        <Checkbox
          id="hide-auto-generated"
          checked={hideAutoGenerated}
          onCheckedChange={(checked: boolean) => setHideAutoGenerated(checked)}
        />
        <Label htmlFor="hide-auto-generated" className="cursor-pointer" style={{ fontSize: "13px" }}>
          Hide auto-generated rooms &amp; statements (scrapers)
        </Label>
      </div>

      <div style={{ padding: "16px 24px", display: "flex", gap: "8px", flexWrap: "wrap" }}>
        <Button
          variant={filter === "all" ? "default" : "outline"}
          size="sm"
          onClick={() => setFilter("all")}
        >
          All ({scopedEvents.length})
        </Button>
        {ALL_TYPES.map((t) => {
          const cfg = TYPE_CONFIG[t];
          return (
            <Button
              key={t}
              variant={filter === t ? "default" : "outline"}
              size="sm"
              onClick={() => setFilter(t)}
            >
              {cfg.label}s ({counts[t] ?? 0})
            </Button>
          );
        })}
      </div>

      <div style={{ flex: 1, padding: "0 24px 24px" }}>
        {loading && (
          <div style={{ textAlign: "center", padding: "48px", color: "#6b7280" }}>Loading…</div>
        )}
        {error && !loading && (
          <div style={{ textAlign: "center", padding: "48px", color: "#ef4444" }}>{error}</div>
        )}
        {!loading && !error && visible.length === 0 && (
          <div style={{ textAlign: "center", padding: "48px", color: "#6b7280" }}>No records found</div>
        )}
        {!loading && !error && visible.length > 0 && (
          <div style={{ backgroundColor: "white", border: "1px solid #e5e7eb", borderRadius: "8px", overflow: "hidden" }}>
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "13px" }}>
              <thead>
                <tr style={{ backgroundColor: "#f3f4f6", borderBottom: "1px solid #e5e7eb" }}>
                  <th style={{ padding: "10px 16px", textAlign: "left", fontWeight: 600, color: "#374151", width: "90px" }}>Type</th>
                  <th style={{ padding: "10px 16px", textAlign: "left", fontWeight: 600, color: "#374151" }}>Details</th>
                  <th style={{ padding: "10px 16px", textAlign: "left", fontWeight: 600, color: "#374151", width: "80px" }}>When</th>
                </tr>
              </thead>
              <tbody>
                {visible.map((event, i) => {
                  const cfg = TYPE_CONFIG[event.type];
                  const Icon = cfg.icon;
                  const isNew = lastReviewedAt !== null && event.timestamp > lastReviewedAt;
                  return (
                    <tr
                      key={`${event.type}-${event.id}-${i}`}
                      style={{
                        borderBottom: i < visible.length - 1 ? "1px solid #f3f4f6" : "none",
                        backgroundColor: isNew ? "#eff6ff" : undefined,
                      }}
                    >
                      <td style={{ padding: "10px 16px" }}>
                        <span style={{ display: "inline-flex", alignItems: "center", gap: "4px", padding: "2px 8px", borderRadius: "9999px", fontSize: "12px", fontWeight: 500 }}
                          className={`${cfg.bg} ${cfg.color}`}>
                          <Icon className="w-3 h-3" />
                          {cfg.label}
                        </span>
                      </td>
                      <td style={{ padding: "10px 16px", color: "#111827", maxWidth: "0", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                        {event.isAutoGenerated && (
                          <span
                            title="Auto-generated by a scraper (Reddit / GGWash)"
                            style={{ display: "inline-flex", alignItems: "center", gap: "3px", padding: "1px 6px", borderRadius: "9999px", fontSize: "11px", fontWeight: 500, color: "#4338ca", backgroundColor: "#e0e7ff", marginRight: "6px" }}
                          >
                            <Bot className="w-3 h-3" />
                            Auto
                          </span>
                        )}
                        <span title={event.label}>{event.label}</span>
                        {event.meta && Object.keys(event.meta).length > 0 && (
                          <span style={{ color: "#9ca3af", fontSize: "11px", marginLeft: "8px" }}>
                            {Object.entries(event.meta).map(([k, v]) => `${k}: ${v}`).join(" · ")}
                          </span>
                        )}
                      </td>
                      <td style={{ padding: "10px 16px", color: "#6b7280", whiteSpace: "nowrap" }}>
                        {formatTime(event.timestamp)}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
