import { DebateRoom, Statement } from "./types.tsx";

export const mockRooms: DebateRoom[] = [
  // SCENARIO 1: New topic, no statements yet - GOOD CANDIDATE
  {
    id: "new-empty-topic",
    topic: "Universal basic income would solve most poverty issues",
    phase: "round1",
    subPhase: undefined,
    gameNumber: 1,
    roundStartTime: Date.now() - 10 * 60 * 1000, // 10 mins ago
    participants: ["user1"],
    hostId: "user1",
    isActive: true,
    createdAt: Date.now() - 15 * 60 * 1000,
    mode: "realtime",
    rantFirst: true,
    endTime: Date.now() + 7 * 24 * 60 * 60 * 1000,
    subHeard: "politics",
  },

  // SCENARIO 2: Active topic, healthy engagement, no AI yet - GOOD CANDIDATE
  {
    id: "active-healthy",
    topic: "Coffee is better than tea in every way",
    phase: "round1",
    subPhase: "voting",
    gameNumber: 1,
    roundStartTime: Date.now() - 45 * 60 * 1000, // 45 mins ago
    participants: ["user1", "user2", "user3", "user4"],
    hostId: "user1",
    isActive: true,
    createdAt: Date.now() - 60 * 60 * 1000,
    mode: "realtime",
    rantFirst: true,
    endTime: Date.now() + 6 * 24 * 60 * 60 * 1000,
    subHeard: "food",
  },

  // SCENARIO 3: Stale topic, low engagement - GOOD CANDIDATE
  {
    id: "stale-low-engagement",
    topic: "Streaming services should release all episodes at once",
    phase: "round1",
    subPhase: undefined,
    gameNumber: 1,
    roundStartTime: Date.now() - 3 * 60 * 60 * 1000, // 3 hours ago
    participants: ["user1", "user2"],
    hostId: "user2",
    isActive: true,
    createdAt: Date.now() - 4 * 60 * 60 * 1000,
    mode: "realtime",
    rantFirst: true,
    endTime: Date.now() + 5 * 24 * 60 * 60 * 1000,
    subHeard: "entertainment",
  },

  // SCENARIO 4: Already has AI statements, balanced - MAYBE
  {
    id: "has-some-ai",
    topic: "Social media does more harm than good",
    phase: "round1",
    subPhase: "voting",
    gameNumber: 1,
    roundStartTime: Date.now() - 2 * 60 * 60 * 1000,
    participants: ["user1", "user2", "user3", "chatgpt"],
    hostId: "user1",
    isActive: true,
    createdAt: Date.now() - 3 * 60 * 60 * 1000,
    mode: "realtime",
    rantFirst: true,
    endTime: Date.now() + 6 * 24 * 60 * 60 * 1000,
    subHeard: "technology",
  },

  // SCENARIO 5: Too many AI statements already - BAD CANDIDATE
  {
    id: "ai-saturated",
    topic: "Climate change is the most urgent issue of our time",
    phase: "round1",
    subPhase: undefined,
    gameNumber: 1,
    roundStartTime: Date.now() - 90 * 60 * 1000,
    participants: ["user1", "chatgpt"],
    hostId: "user1",
    isActive: true,
    createdAt: Date.now() - 2 * 60 * 60 * 1000,
    mode: "realtime",
    rantFirst: true,
    endTime: Date.now() + 6 * 24 * 60 * 60 * 1000,
    subHeard: "environment",
  },

  // SCENARIO 6: Very active, lots of engagement - BAD CANDIDATE (doesn't need AI)
  {
    id: "super-active",
    topic: "Star Wars is better than Star Trek",
    phase: "round1",
    subPhase: "voting",
    gameNumber: 1,
    roundStartTime: Date.now() - 20 * 60 * 1000,
    participants: ["user1", "user2", "user3", "user4", "user5", "user6", "user7", "user8"],
    hostId: "user3",
    isActive: true,
    createdAt: Date.now() - 30 * 60 * 1000,
    mode: "realtime",
    rantFirst: true,
    endTime: Date.now() + 7 * 24 * 60 * 60 * 1000,
    subHeard: "entertainment",
  },

  // SCENARIO 7: Old topic, no recent activity - MAYBE
  {
    id: "old-inactive",
    topic: "Working from home should be the default",
    phase: "round1",
    subPhase: undefined,
    gameNumber: 1,
    roundStartTime: Date.now() - 24 * 60 * 60 * 1000, // 1 day ago
    participants: ["user1", "user2"],
    hostId: "user1",
    isActive: true,
    createdAt: Date.now() - 25 * 60 * 60 * 1000,
    mode: "realtime",
    rantFirst: true,
    endTime: Date.now() + 6 * 24 * 60 * 60 * 1000,
    subHeard: "work",
  },

  // SCENARIO 8: Medium age, few statements, no votes - GOOD CANDIDATE
  {
    id: "low-votes",
    topic: "Video games are legitimate art forms",
    phase: "round1",
    subPhase: undefined,
    gameNumber: 1,
    roundStartTime: Date.now() - 6 * 60 * 60 * 1000, // 6 hours ago
    participants: ["user1", "user2", "user3"],
    hostId: "user2",
    isActive: true,
    createdAt: Date.now() - 7 * 60 * 60 * 1000,
    mode: "realtime",
    rantFirst: true,
    endTime: Date.now() + 5 * 24 * 60 * 60 * 1000,
    subHeard: "entertainment",
  },

  // SCENARIO 9: Controversial topic, high engagement - BAD CANDIDATE
  {
    id: "controversial-active",
    topic: "Cryptocurrency will replace traditional banking",
    phase: "round1",
    subPhase: "voting",
    gameNumber: 1,
    roundStartTime: Date.now() - 40 * 60 * 1000,
    participants: ["user1", "user2", "user3", "user4", "user5"],
    hostId: "user4",
    isActive: true,
    createdAt: Date.now() - 50 * 60 * 1000,
    mode: "realtime",
    rantFirst: true,
    endTime: Date.now() + 7 * 24 * 60 * 60 * 1000,
    subHeard: "finance",
  },

  // SCENARIO 10: Recently had AI injection, cooling off - BAD CANDIDATE
  {
    id: "recent-ai-injection",
    topic: "Public transportation should be free",
    phase: "round1",
    subPhase: undefined,
    gameNumber: 1,
    roundStartTime: Date.now() - 30 * 60 * 1000,
    participants: ["user1", "user2", "chatgpt"],
    hostId: "user1",
    isActive: true,
    createdAt: Date.now() - 2 * 60 * 60 * 1000,
    mode: "realtime",
    rantFirst: true,
    endTime: Date.now() + 6 * 24 * 60 * 60 * 1000,
    subHeard: "politics",
  },
];

export const mockStatements: Record<string, Statement[]> = {
  // SCENARIO 1: Empty - no statements
  "new-empty-topic": [],

  // SCENARIO 2: Active, healthy, diverse opinions, good votes
  "active-healthy": [
    {
      id: "stmt-ah-1",
      text: "Coffee has way more caffeine and gets you going in the morning",
      author: "user1",
      roomId: "active-healthy",
      timestamp: Date.now() - 40 * 60 * 1000,
      agrees: 5,
      disagrees: 2,
      passes: 0,
      superAgrees: 1,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-ah-2",
      text: "Tea has more variety and health benefits, plus it's gentler",
      author: "user2",
      roomId: "active-healthy",
      timestamp: Date.now() - 35 * 60 * 1000,
      agrees: 4,
      disagrees: 3,
      passes: 1,
      superAgrees: 0,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-ah-3",
      text: "Coffee culture is way more developed - there's a reason Starbucks exists",
      author: "user3",
      roomId: "active-healthy",
      timestamp: Date.now() - 30 * 60 * 1000,
      agrees: 3,
      disagrees: 2,
      passes: 2,
      superAgrees: 0,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-ah-4",
      text: "Tea ceremonies have existed for thousands of years, coffee is just trendy",
      author: "user4",
      roomId: "active-healthy",
      timestamp: Date.now() - 25 * 60 * 1000,
      agrees: 2,
      disagrees: 4,
      passes: 1,
      superAgrees: 1,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-ah-5",
      text: "Coffee gives you energy crashes, tea provides sustained energy",
      author: "user2",
      roomId: "active-healthy",
      timestamp: Date.now() - 20 * 60 * 1000,
      agrees: 6,
      disagrees: 1,
      passes: 0,
      superAgrees: 2,
      voters: {},
      round: 1,
    },
  ],

  // SCENARIO 3: Stale, only 2 statements, low votes
  "stale-low-engagement": [
    {
      id: "stmt-sl-1",
      text: "Binge watching is how shows are meant to be consumed now",
      author: "user1",
      roomId: "stale-low-engagement",
      timestamp: Date.now() - 2.5 * 60 * 60 * 1000,
      agrees: 1,
      disagrees: 0,
      passes: 1,
      superAgrees: 0,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-sl-2",
      text: "Weekly releases build anticipation and community discussion",
      author: "user2",
      roomId: "stale-low-engagement",
      timestamp: Date.now() - 2 * 60 * 60 * 1000,
      agrees: 1,
      disagrees: 1,
      passes: 0,
      superAgrees: 0,
      voters: {},
      round: 1,
    },
  ],

  // SCENARIO 4: Has some AI, balanced mix
  "has-some-ai": [
    {
      id: "stmt-ai-1",
      text: "Social media connects people across the globe instantly",
      author: "user1",
      roomId: "has-some-ai",
      timestamp: Date.now() - 2.5 * 60 * 60 * 1000,
      agrees: 3,
      disagrees: 2,
      passes: 0,
      superAgrees: 1,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-ai-2",
      text: "Studies show increased anxiety and depression correlate with social media use",
      author: "chatgpt",
      roomId: "has-some-ai",
      timestamp: Date.now() - 2 * 60 * 60 * 1000,
      agrees: 5,
      disagrees: 1,
      passes: 1,
      superAgrees: 0,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-ai-3",
      text: "It's created echo chambers where people only see views they agree with",
      author: "user2",
      roomId: "has-some-ai",
      timestamp: Date.now() - 1.5 * 60 * 60 * 1000,
      agrees: 4,
      disagrees: 2,
      passes: 0,
      superAgrees: 1,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-ai-4",
      text: "Social movements like #MeToo wouldn't have happened without social media",
      author: "user3",
      roomId: "has-some-ai",
      timestamp: Date.now() - 1 * 60 * 60 * 1000,
      agrees: 6,
      disagrees: 0,
      passes: 1,
      superAgrees: 2,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-ai-5",
      text: "The algorithms prioritize engagement over accuracy, spreading misinformation",
      author: "chatgpt",
      roomId: "has-some-ai",
      timestamp: Date.now() - 45 * 60 * 1000,
      agrees: 5,
      disagrees: 1,
      passes: 0,
      superAgrees: 1,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-ai-6",
      text: "I've reconnected with old friends I never would have found otherwise",
      author: "user1",
      roomId: "has-some-ai",
      timestamp: Date.now() - 30 * 60 * 1000,
      agrees: 3,
      disagrees: 0,
      passes: 2,
      superAgrees: 0,
      voters: {},
      round: 1,
    },
  ],

  // SCENARIO 5: AI saturated - 80% AI statements
  "ai-saturated": [
    {
      id: "stmt-sat-1",
      text: "Global temperatures have risen 1.1°C since pre-industrial times",
      author: "chatgpt",
      roomId: "ai-saturated",
      timestamp: Date.now() - 85 * 60 * 1000,
      agrees: 2,
      disagrees: 0,
      passes: 0,
      superAgrees: 0,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-sat-2",
      text: "We're already seeing increased extreme weather events",
      author: "chatgpt",
      roomId: "ai-saturated",
      timestamp: Date.now() - 80 * 60 * 1000,
      agrees: 3,
      disagrees: 0,
      passes: 0,
      superAgrees: 1,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-sat-3",
      text: "The science is settled - 97% of climate scientists agree",
      author: "chatgpt",
      roomId: "ai-saturated",
      timestamp: Date.now() - 75 * 60 * 1000,
      agrees: 2,
      disagrees: 0,
      passes: 1,
      superAgrees: 0,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-sat-4",
      text: "Future generations will suffer if we don't act now",
      author: "chatgpt",
      roomId: "ai-saturated",
      timestamp: Date.now() - 70 * 60 * 1000,
      agrees: 3,
      disagrees: 0,
      passes: 0,
      superAgrees: 1,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-sat-5",
      text: "I think we need immediate policy changes at the government level",
      author: "user1",
      roomId: "ai-saturated",
      timestamp: Date.now() - 65 * 60 * 1000,
      agrees: 2,
      disagrees: 0,
      passes: 0,
      superAgrees: 0,
      voters: {},
      round: 1,
    },
  ],

  // SCENARIO 6: Super active - lots of human engagement
  "super-active": [
    {
      id: "stmt-sa-1",
      text: "Star Wars has better world-building and mythology",
      author: "user1",
      roomId: "super-active",
      timestamp: Date.now() - 18 * 60 * 1000,
      agrees: 8,
      disagrees: 3,
      passes: 1,
      superAgrees: 2,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-sa-2",
      text: "Star Trek actually explores moral and philosophical questions",
      author: "user2",
      roomId: "super-active",
      timestamp: Date.now() - 17 * 60 * 1000,
      agrees: 7,
      disagrees: 4,
      passes: 1,
      superAgrees: 1,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-sa-3",
      text: "The Force is way cooler than any Trek technology",
      author: "user3",
      roomId: "super-active",
      timestamp: Date.now() - 16 * 60 * 1000,
      agrees: 6,
      disagrees: 5,
      passes: 1,
      superAgrees: 3,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-sa-4",
      text: "Trek has better character development and ensemble casts",
      author: "user4",
      roomId: "super-active",
      timestamp: Date.now() - 15 * 60 * 1000,
      agrees: 5,
      disagrees: 6,
      passes: 1,
      superAgrees: 1,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-sa-5",
      text: "Star Wars revolutionized special effects and cinema",
      author: "user5",
      roomId: "super-active",
      timestamp: Date.now() - 14 * 60 * 1000,
      agrees: 9,
      disagrees: 2,
      passes: 1,
      superAgrees: 2,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-sa-6",
      text: "Trek's vision of the future is optimistic and inspiring",
      author: "user6",
      roomId: "super-active",
      timestamp: Date.now() - 13 * 60 * 1000,
      agrees: 6,
      disagrees: 4,
      passes: 2,
      superAgrees: 1,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-sa-7",
      text: "The lightsaber duels alone make Star Wars superior",
      author: "user7",
      roomId: "super-active",
      timestamp: Date.now() - 12 * 60 * 1000,
      agrees: 7,
      disagrees: 3,
      passes: 2,
      superAgrees: 2,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-sa-8",
      text: "Trek has 800+ episodes, Star Wars can't compete with that depth",
      author: "user8",
      roomId: "super-active",
      timestamp: Date.now() - 11 * 60 * 1000,
      agrees: 5,
      disagrees: 6,
      passes: 1,
      superAgrees: 0,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-sa-9",
      text: "John Williams' score is the most iconic in cinema history",
      author: "user1",
      roomId: "super-active",
      timestamp: Date.now() - 10 * 60 * 1000,
      agrees: 10,
      disagrees: 1,
      passes: 1,
      superAgrees: 3,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-sa-10",
      text: "Trek predicted cell phones, tablets, and video calls decades early",
      author: "user2",
      roomId: "super-active",
      timestamp: Date.now() - 9 * 60 * 1000,
      agrees: 8,
      disagrees: 2,
      passes: 2,
      superAgrees: 1,
      voters: {},
      round: 1,
    },
  ],

  // SCENARIO 7: Old, inactive - 3 old statements, no recent activity
  "old-inactive": [
    {
      id: "stmt-oi-1",
      text: "Commuting wastes 2+ hours a day that could be productive",
      author: "user1",
      roomId: "old-inactive",
      timestamp: Date.now() - 23 * 60 * 60 * 1000,
      agrees: 2,
      disagrees: 0,
      passes: 0,
      superAgrees: 0,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-oi-2",
      text: "Office collaboration is irreplaceable for creative work",
      author: "user2",
      roomId: "old-inactive",
      timestamp: Date.now() - 22 * 60 * 60 * 1000,
      agrees: 1,
      disagrees: 1,
      passes: 0,
      superAgrees: 0,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-oi-3",
      text: "Remote work gives better work-life balance",
      author: "user1",
      roomId: "old-inactive",
      timestamp: Date.now() - 21 * 60 * 60 * 1000,
      agrees: 2,
      disagrees: 0,
      passes: 0,
      superAgrees: 1,
      voters: {},
      round: 1,
    },
  ],

  // SCENARIO 8: Medium age, few statements, almost no votes
  "low-votes": [
    {
      id: "stmt-lv-1",
      text: "Games like The Last of Us have storytelling as good as any movie",
      author: "user1",
      roomId: "low-votes",
      timestamp: Date.now() - 5.5 * 60 * 60 * 1000,
      agrees: 0,
      disagrees: 0,
      passes: 1,
      superAgrees: 0,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-lv-2",
      text: "Interactive media is a fundamentally different medium",
      author: "user2",
      roomId: "low-votes",
      timestamp: Date.now() - 5 * 60 * 60 * 1000,
      agrees: 1,
      disagrees: 0,
      passes: 0,
      superAgrees: 0,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-lv-3",
      text: "Most games are still just mindless entertainment",
      author: "user3",
      roomId: "low-votes",
      timestamp: Date.now() - 4.5 * 60 * 60 * 1000,
      agrees: 0,
      disagrees: 1,
      passes: 1,
      superAgrees: 0,
      voters: {},
      round: 1,
    },
  ],

  // SCENARIO 9: Controversial, very active - lots of heated debate
  "controversial-active": [
    {
      id: "stmt-ca-1",
      text: "Bitcoin is already replacing remittance services in developing countries",
      author: "user1",
      roomId: "controversial-active",
      timestamp: Date.now() - 35 * 60 * 1000,
      agrees: 6,
      disagrees: 4,
      passes: 0,
      superAgrees: 2,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-ca-2",
      text: "Crypto is mostly used for crime and speculation, not real transactions",
      author: "user2",
      roomId: "controversial-active",
      timestamp: Date.now() - 33 * 60 * 1000,
      agrees: 5,
      disagrees: 5,
      passes: 0,
      superAgrees: 1,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-ca-3",
      text: "Traditional banks are scared because they see the writing on the wall",
      author: "user3",
      roomId: "controversial-active",
      timestamp: Date.now() - 30 * 60 * 1000,
      agrees: 7,
      disagrees: 3,
      passes: 0,
      superAgrees: 2,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-ca-4",
      text: "The volatility alone makes it useless as actual currency",
      author: "user4",
      roomId: "controversial-active",
      timestamp: Date.now() - 28 * 60 * 1000,
      agrees: 4,
      disagrees: 6,
      passes: 0,
      superAgrees: 0,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-ca-5",
      text: "DeFi is already offering better interest rates than any bank",
      author: "user5",
      roomId: "controversial-active",
      timestamp: Date.now() - 25 * 60 * 1000,
      agrees: 6,
      disagrees: 3,
      passes: 1,
      superAgrees: 1,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-ca-6",
      text: "Most people don't want to be their own bank, it's too much responsibility",
      author: "user2",
      roomId: "controversial-active",
      timestamp: Date.now() - 22 * 60 * 1000,
      agrees: 5,
      disagrees: 4,
      passes: 1,
      superAgrees: 1,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-ca-7",
      text: "Smart contracts eliminate the need for middlemen",
      author: "user1",
      roomId: "controversial-active",
      timestamp: Date.now() - 20 * 60 * 1000,
      agrees: 7,
      disagrees: 2,
      passes: 1,
      superAgrees: 2,
      voters: {},
      round: 1,
    },
  ],

  // SCENARIO 10: Recently had AI injection - 2 AI statements added 20-25 mins ago
  "recent-ai-injection": [
    {
      id: "stmt-rai-1",
      text: "Public transit reduces traffic and pollution significantly",
      author: "user1",
      roomId: "recent-ai-injection",
      timestamp: Date.now() - 1.5 * 60 * 60 * 1000,
      agrees: 3,
      disagrees: 1,
      passes: 0,
      superAgrees: 0,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-rai-2",
      text: "Free public transit has been successfully implemented in Luxembourg and Estonian cities",
      author: "chatgpt",
      roomId: "recent-ai-injection",
      timestamp: Date.now() - 25 * 60 * 1000,
      agrees: 4,
      disagrees: 0,
      passes: 0,
      superAgrees: 1,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-rai-3",
      text: "Studies show free transit increases ridership by 20-50% depending on the city",
      author: "chatgpt",
      roomId: "recent-ai-injection",
      timestamp: Date.now() - 20 * 60 * 1000,
      agrees: 3,
      disagrees: 0,
      passes: 1,
      superAgrees: 0,
      voters: {},
      round: 1,
    },
    {
      id: "stmt-rai-4",
      text: "Someone still has to pay for it through taxes",
      author: "user2",
      roomId: "recent-ai-injection",
      timestamp: Date.now() - 15 * 60 * 1000,
      agrees: 2,
      disagrees: 2,
      passes: 0,
      superAgrees: 0,
      voters: {},
      round: 1,
    },
  ],
};